[package]
name = 'calculator_l05'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0xa4af459e5b8212ab24f3f40409b22ac828245d348f3eccdd2bc5d0a36d5acbeb"
std = "0x1"